// IEEE Std 1800-2012
//   12. Procedural programming statements
//    12.4 Conditional if–else statement
//     12.4.2 unique-if, unique0-if, and priority-if
//      12.4.2.1 Violation reports generated by unique-if, unique0-if, and priority-if constructs

// ! TYPE: POSITIVE

module top;

  logic [2:0] a, not_a, b, c, z;

  always_comb begin
    for (int j = 0; j < 3; j++)
      not_a[j] = !a[j];
  end

  always_comb begin : a1
    for (int j = 0; j < 3; j++)
      unique if (a[j])
        z[j] = a[j] | b[j];
      else if (not_a[j])
        z[j] = a[j] | c[j];
  end

endmodule
