/*
 * Copyright 2025 ISP RAS (http://www.ispras.ru)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// IEEE Std 1800-2012
//   12. Procedural programming statements
//    12.5 Case statement
//     12.5.3 unique-case, unique0-case, and priority-case
//      12.5.3.1 Violation reports generated by unique-case, unique0-case, and priority-case constructs

// ! TYPE: POSITIVE

module top;

  logic a, not_a, b, c, z;

  always_comb begin
    not_a = !a;
  end

  always_comb begin : a1
    unique case (1'b1)
      a : z = b;
      not_a : z = c;
    endcase
  end

endmodule
