// IEEE Std 1800-2012
//   12. Procedural programming statements
//    12.5 Case statement
//     12.5.3 unique-case, unique0-case, and priority-case
//      12.5.3.1 Violation reports generated by unique-case, unique0-case, and priority-case constructs

// ! TYPE: POSITIVE

module top;

  logic a, not_a, b, c, z;

  always_comb begin
    not_a = !a;
  end

  always_comb begin : a1
    unique case (1'b1)
      a : z = b;
      not_a : z = c;
    endcase
  end

endmodule
