// IEEE Std 1800-2012
//   12. Procedural programming statements
//    12.4 Conditional if–else statement
//     12.4.2 unique-if, unique0-if, and priority-if
//      12.4.2.1 Violation reports generated by unique-if,
//               unique0-if, and priority-if constructs

// ! TYPE: POSITIVE

module top;

  logic a, not_a, b, c, z;

  always_comb begin
    not_a = !a;
  end

  always_comb begin : a1
    u1: unique if (a)
      z = a | b;
    else if (not_a)
      z = a | c;
  end

endmodule
