/*
 * Copyright 2025 ISP RAS (http://www.ispras.ru)
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *     http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

// IEEE Std 1800-2012
//   12. Procedural programming statements
//    12.4 Conditional if–else statement
//     12.4.2 unique-if, unique0-if, and priority-if
//      12.4.2.1 Violation reports generated by unique-if, unique0-if, and priority-if constructs

// ! TYPE: POSITIVE

module top;

  logic [2:0] a, not_a, b, c, z;

  always_comb begin
    for (int j = 0; j < 3; j++)
      not_a[j] = !a[j];
  end

  always_comb begin : a1
    for (int j = 0; j < 3; j++)
      unique if (a[j])
        z[j] = a[j] | b[j];
      else if (not_a[j])
        z[j] = a[j] | c[j];
  end

endmodule
